name: Synchronize Uni branch

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: uni
          fetch-depth: 0
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git pull origin master
      - run: sed -i 's/import addon="xbmc.python" version="3.0.0" \//!--import addon="xbmc.python" version="3.0.0" \/--/' addon.xml
      - run: git add -A
      - run: git diff-index --quiet HEAD || git commit -m "addon.xml auto update for Uni"
      - run: git push --force
